# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.name={{.ProjectName}} -X main.version={{.Version}}
    goos:
      - darwin
      - dragonfly
      - freebsd
      - linux
      - nacl
      - netbsd
      - openbsd
      - plan9
      - solaris
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
    goarm:
      - 5
      - 6
      - 7
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
archive:
  replacements:
    386: i386
    amd64: x86_64
